name: mom
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< Updated upstream
  provider: ^6.1.3 # لإدارة الحالة
  audioplayers: ^3.0.1 # لتشغيل الصوتيات
  http: ^0.15.5 # (إذا كنت بحاجة لتحميل الصوتيات من الإنترنت)
=======
  provider: ^6.1.3
  audioplayers: ^1.0.1 # الإصدار المتوافق مع Flutter 3.7.3
  http: ^0.15.0
>>>>>>> Stashed changes

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/quran.json
  #  - assets/audio/audio1.mp3
   # - assets/audio/audio2.mp3
