name: mom
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2 # لإدارة الحالة
  audioplayers: ^6.1.0 # لتشغيل الصوتيات
  http: ^1.2.2 # تحميل الصوتيات من الإنترنت

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/quran.json
  #  - assets/audio/audio1.mp3
  #  - assets/audio/audio2.mp3
